/* 
 * Copyright 2021 The LipidCompass Developers.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.lipidcompass.data.model.submission;

import lombok.Data;

/**
 * A validation message generated by any of the validation processes for
 * submissions.
 *
 * @author nilshoffmann
 */
@Data
public class ValidationMessage {

    public static enum Level {
        INFO, WARN, ERROR;
    }

    public static enum Source {
        MZTAB_M_VALIDATION,
        INPUT_FILE_VALIDATION,
        POST_HOC_CHECKS_VALIDATION
    }

    private Level level;
    private Source source;
    private String message;
    private String code;

}
