/**
 * LipidCompass Search API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './pageMetadata';
import { Link } from './link';
import { PagedModelEntityModelMzTabResultDocumentEmbedded } from './pagedModelEntityModelMzTabResultDocumentEmbedded';


export interface PagedModelEntityModelMzTabResultDocument { 
    _embedded?: PagedModelEntityModelMzTabResultDocumentEmbedded;
    _links?: { [key: string]: Link; };
    page?: PageMetadata;
}

