/**
 * LipidCompass Search API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateResponseExceptionCauseStackTraceInner } from './updateResponseExceptionCauseStackTraceInner';
import { UpdateResponseExceptionCause } from './updateResponseExceptionCause';
import { UpdateResponseExceptionCauseSuppressedInner } from './updateResponseExceptionCauseSuppressedInner';


export interface UpdateResponseException { 
    cause?: UpdateResponseExceptionCause;
    stackTrace?: Array<UpdateResponseExceptionCauseStackTraceInner>;
    message?: string;
    suppressed?: Array<UpdateResponseExceptionCauseSuppressedInner>;
    localizedMessage?: string;
}

