/**
 * LipidCompass Search API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateResponseExceptionCauseStackTrace } from './updateResponseExceptionCauseStackTrace';


export interface UpdateResponseExceptionCauseSuppressed { 
    stackTrace?: Array<UpdateResponseExceptionCauseStackTrace>;
    message?: string;
    localizedMessage?: string;
}

