/**
 * LipidCompass Data Importer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExitStatus } from './exitStatus';
import { EntityModelJobExecutionDtoFailureExceptionsInner } from './entityModelJobExecutionDtoFailureExceptionsInner';
import { JobParameter } from './jobParameter';
import { Link } from './link';


export interface EntityModelJobExecutionDto { 
    executionId?: number;
    jobId?: number;
    jobName?: string;
    status?: EntityModelJobExecutionDto.StatusEnum;
    jobParameters?: { [key: string]: JobParameter; };
    createTime?: string;
    startTime?: string;
    endTime?: string;
    lastUpdateTime?: string;
    exitStatus?: ExitStatus;
    failureExceptions?: Array<EntityModelJobExecutionDtoFailureExceptionsInner>;
    _links?: { [key: string]: Link; };
}
export namespace EntityModelJobExecutionDto {
    export type StatusEnum = 'COMPLETED' | 'STARTING' | 'STARTED' | 'STOPPING' | 'STOPPED' | 'FAILED' | 'ABANDONED' | 'UNKNOWN' | '11184809';
    export const StatusEnum = {
        COMPLETED: 'COMPLETED' as StatusEnum,
        STARTING: 'STARTING' as StatusEnum,
        STARTED: 'STARTED' as StatusEnum,
        STOPPING: 'STOPPING' as StatusEnum,
        STOPPED: 'STOPPED' as StatusEnum,
        FAILED: 'FAILED' as StatusEnum,
        ABANDONED: 'ABANDONED' as StatusEnum,
        UNKNOWN: 'UNKNOWN' as StatusEnum,
        unknown_default_open_api: '11184809' as StatusEnum
    };
}


