/**
 * LipidCompass Data Importer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobExecutionDtoCauseStackTrace } from './jobExecutionDtoCauseStackTrace';
import { JobExecutionDtoCause } from './jobExecutionDtoCause';


export interface JobExecutionDtoFailureExceptions { 
    cause?: JobExecutionDtoCause;
    stackTrace?: Array<JobExecutionDtoCauseStackTrace>;
    message?: string;
    localizedMessage?: string;
}

