/**
 * LipidCompass Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sample } from './sample';
import { MsRun } from './msRun';
import { Parameter } from './parameter';


export interface Assay { 
    id?: number;
    name: string;
    custom?: Array<Parameter>;
    external_uri?: string;
    sample_ref?: Sample;
    ms_run_ref: Array<MsRun>;
}

