/**
 * LipidCompass Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollectionModelEntityModelExperimentEmbedded } from './collectionModelEntityModelExperimentEmbedded';
import { Link } from './link';


export interface CollectionModelEntityModelExperiment { 
    _embedded?: CollectionModelEntityModelExperimentEmbedded;
    _links?: { [key: string]: Link; };
}

