/**
 * LipidCompass Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CollectionModelLevelEmbedded { 
    levels?: Array<CollectionModelLevelEmbedded.LevelsEnum>;
}
export namespace CollectionModelLevelEmbedded {
    export type LevelsEnum = 'CATEGORY' | 'CLASS' | 'SPECIES' | 'MOLECULARSUBSPECIES' | 'STRUCTURALSUBSPECIES' | 'ISOMERICSUBSPECIES' | '11184809';
    export const LevelsEnum = {
        CATEGORY: 'CATEGORY' as LevelsEnum,
        CLASS: 'CLASS' as LevelsEnum,
        SPECIES: 'SPECIES' as LevelsEnum,
        MOLECULARSUBSPECIES: 'MOLECULARSUBSPECIES' as LevelsEnum,
        STRUCTURALSUBSPECIES: 'STRUCTURALSUBSPECIES' as LevelsEnum,
        ISOMERICSUBSPECIES: 'ISOMERICSUBSPECIES' as LevelsEnum,
        unknown_default_open_api: '11184809' as LevelsEnum
    };
}


