/**
 * LipidCompass Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CvParameter } from './cvParameter';
import { Submission } from './submission';
import { MzTabAssay } from './mzTabAssay';
import { Link } from './link';
import { Lipid } from './lipid';
import { MzTabStudyVariable } from './mzTabStudyVariable';


export interface EntityModelLipidQuantity { 
    id?: string;
    arangoId?: string;
    transactionUuid: string;
    visibility?: EntityModelLipidQuantity.VisibilityEnum;
    lipids?: Array<Lipid>;
    cvParameters?: Array<CvParameter>;
    nativeId?: string;
    mzTabResultId?: string;
    smlId?: number;
    assay?: MzTabAssay;
    studyVariable?: MzTabStudyVariable;
    assayQuantity?: number;
    assayRelativeQuantity?: number;
    quantificationUnit?: CvParameter;
    identificationReliability?: string;
    bestIdentificationConfidenceMeasure?: CvParameter;
    bestIdConfidenceValue?: number;
    submission?: Submission;
    revision?: string;
    dateCreated?: string;
    dateLastModified?: string;
    createdBy?: string;
    updatedBy?: string;
    _links?: { [key: string]: Link; };
}
export namespace EntityModelLipidQuantity {
    export type VisibilityEnum = 'PRIVATE' | 'RESTRICTED' | 'PUBLIC' | '11184809';
    export const VisibilityEnum = {
        PRIVATE: 'PRIVATE' as VisibilityEnum,
        RESTRICTED: 'RESTRICTED' as VisibilityEnum,
        PUBLIC: 'PUBLIC' as VisibilityEnum,
        unknown_default_open_api: '11184809' as VisibilityEnum
    };
}


