/**
 * LipidCompass Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Comment } from './comment';
import { Parameter } from './parameter';
import { OptColumnMapping } from './optColumnMapping';
import { Link } from './link';
import { SpectraRef } from './spectraRef';


export interface EntityModelSmallMoleculeEvidence { 
    prefix?: EntityModelSmallMoleculeEvidence.PrefixEnum;
    header_prefix?: EntityModelSmallMoleculeEvidence.HeaderPrefixEnum;
    sme_id: number;
    evidence_input_id: string;
    database_identifier: string;
    chemical_formula?: string;
    smiles?: string;
    inchi?: string;
    chemical_name?: string;
    uri?: string;
    derivatized_form?: Parameter;
    adduct_ion?: string;
    exp_mass_to_charge: number;
    charge: number;
    theoretical_mass_to_charge: number;
    spectra_ref: Array<SpectraRef>;
    identification_method: Parameter;
    ms_level: Parameter;
    id_confidence_measure?: Array<number>;
    rank: number;
    opt?: Array<OptColumnMapping>;
    comment?: Array<Comment>;
    _links?: { [key: string]: Link; };
}
export namespace EntityModelSmallMoleculeEvidence {
    export type PrefixEnum = 'SME' | '11184809';
    export const PrefixEnum = {
        SME: 'SME' as PrefixEnum,
        unknown_default_open_api: '11184809' as PrefixEnum
    };
    export type HeaderPrefixEnum = 'SEH' | '11184809';
    export const HeaderPrefixEnum = {
        SEH: 'SEH' as HeaderPrefixEnum,
        unknown_default_open_api: '11184809' as HeaderPrefixEnum
    };
}


