# 
# Copyright 2021 The LipidCompass Developers.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# Development profile configuration file for Lipid Compass Dataimporter.
---
logging:
    level:
        org.springframework: INFO
        logging.level.de.isas.lipidomics.palinom: WARN
        logging.level.de.isas.lipidomics.palinom.sumformula: OFF
        logging.level.de.isas.lipidcompass.backend.audit: INFO
        logging.level.de.isas.lipidcompass.batch: INFO
        logging.level.de.isas.lipidcompass.batch.data.importer.swisslipids: INFO
        logging.level.de.isas.lipidcompass.batch.data.importer.utilities: INFO

spring:
    aop:
        proxy-target-class: true
    application:
        name: lipidcompass-data-importer

    batch:
        job:
            enabled: false
        jdbc:
            initialize-schema: ALWAYS
    cloud:
        config:
            enabled: false
    data:
        solr:
            host: ${SOLR_URI:http://127.0.0.1:8983/solr,http://127.0.0.1:8984/solr}
            zk-host: ${ZK_HOST:127.0.0.1:28181}

    datasource:
        url: jdbc:h2:file:${BATCH_DATABASE_DIR:/var/data/lipidcompass/batch/lipid-compass-data-importer-h2-db}
        username: lcadmin
        password: ${docker-secret.lipidcompass_prod_infra_batchdb_pw}
        driver-class-name: org.h2.Driver

    devtools:
        add-properties: false 
    h2:
        console:
            enabled: false
            path: /h2

    jpa:
        hibernate:
            ddl-auto: update
    mail:
        host: mail.lifs-tools.org
        port: 25
        username: ${docker-secret.lipidcompass_prod_mail_user}
        password: ${docker-secret.lipidcompass_prod_mail_password}
        smtp:
            auth: true
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
                        required: true
    mvc:
        throw-exception-if-no-handler-found: true

    security:
        oauth2:
            # register keycloak as an OAUTH2 authorization server, gateway acts as a client to extract role information
            client:
                registration:
                    keycloak:
                        client-id: lipidcompass
                        client-secret: ${docker-secret.lipidcompass_prod_keycloak_client_secret}                        
                        authorization-grant-type: authorization_code
                        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                        scope: openid,profile,email
                provider:
                    keycloak:
                        # https://medium.com/@hantsy/secures-your-application-with-spring-security-5-and-keycloak-2804ee912b0f and https://github.com/hantsy/keycloak-springsecurity5-sample
                        authorization-uri: https://lifs-tools.org/auth/realms/lifs/protocol/openid-connect/auth
                        token-uri: https://lifs-tools.org/realms/lifs/protocol/openid-connect/token
                        user-info-uri: https://lifs-tools.org/auth/realms/lifs/protocol/openid-connect/userinfo
                        jwk-set-uri: https://lifs-tools.org/auth/realms/lifs/protocol/openid-connect/certs
                        user-name-attribute: preferred_username
                        user-info-authentication-method: form
            # gateway acts as an OAUTH2 resourceserver, protecting and proxying to downstream services, jwts are validated
            resourceserver:
                jwt:
                    # settings for oauth2 resourcesserver (https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver-jwt-jwkseturi)
                    issuer-uri: https://lifs-tools.org/auth/realms/lifs
                    jwk-set-uri: https://lifs-tools.org/auth/realms/lifs/protocol/openid-connect/certs

server:
    port: 8088
    forward-headers-strategy: native

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:28092/eureka}
    instance:
        preferIpAddress: true
        homePageUrlPath: ${server.servlet.contextPath}

management:
    endpoints:
        enabled-by-default: false
    endpoint:
        info:
            enabled: true

lipidcompass:
    data-importer:
        api:
            version: 1
    systemUserName: ${LIPIDCOMPASS_SYSTEM_USER}
    # alternatively, using docker secret: ${docker-secret.lipidcompass_dev_systemuser_password}
    systemUserPassword: ${docker-secret.lipidcompass_prod_system_user_pw}
    systemUserEmail: "contact@lifs-tools.org"
    systemAdminName: ${LIPIDCOMPASS_SYSTEM_ADMIN}
    # alternatively, using docker secret: 
    systemAdminPassword: ${docker-secret.lipidcompass_prod_system_admin_pw}
    systemAdminEmail: "contact@lifs-tools.org"

arangodb:
    host: ${ARANGODB_HOST:arangodb}
    port: ${ARANGODB_PORT:28091}
    timeout: ${ARANGODB_TIMEOUT:5000}
    user: ${ARANGODB_USER:root}
    # docker secret lipidcompass_prod_infra_arangodb needs to exist locally
    password: ${docker-secret.lipidcompass_prod_infra_arangodb_pw}
    jwt: 
    #${ARANGODB_JWT:docker-secret.lipidcompass_prod_arangodb_jwt_token_secret}
    useSsl: ${ARANGODB_USE_SSL:false}
    database: lipidcompass
    truncate: false
    maxconnections: 20
    connectionTtl: 300000
    keepAliveInterval: 1800
    chunksize: 30000    

batch:
    config:
        package:
            javaconfig: org.lipidcompass.batch.config.jobs

swissLipids:
    import:
        dir: /var/data/lipidcompass/import/external/SwissLipids
lipidMaps:
    import:
        dir: /var/data/lipidcompass/import/external/LipidMaps
        chunksize: 5000
mzTab:
    import:
        dir: /var/data/lipidcompass/import/submissions

#solr:
#    import:
#        chunksize: 50000
#    backupLocation: /var/solr/backup
## use CLOUD to switch to distributed solr, STANDALONE for single node mode
#    mode: CLOUD
#    collections: lc-lipid-quantities, lc-lipidmaps, lc-lipids, lc-mztab, lc-swisslipids
#    host: ${SOLR_URI:http://localhost:28093/solr}
#    mztab: 
#        core: ${SOLR_MZTAB_CORE:lc-mztab}
#    lipids:
#        core: ${SOLR_LIPIDS_CORE:lc-lipids}
#    lipidmaps:
#        core: ${SOLR_LIPIDMAPS_CORE:lc-lipidmaps}
#    swisslipids:
#        core: ${SOLR_SWISSLIPIDS_CORE:lc-swisslipids}
#    lipidquantities:
#        core: ${SOLR_LIPIDQUANTITIES_CORE:lc-lipid-quantities}
        
minio:
    endpoint: ${MINIO_ENDPOINT:minio1}
    port: ${MINIO_PORT:9000}
    accessKey: ${docker-secret.lipidcompass_prod_infra_minio_password}
    secretKey: ${docker-secret.lipidcompass_prod_infra_minio_user}
    useHttps: ${MINIO_USE_HTTPS:false}
    defaultBucketName: ${MINIO_DEFAULT_BUCKET_NAME:lipidcompass}
    maxFileSize: ${MINIO_MAX_FILE_SIZE:786187}
    tmpDir: ${java.io.tmpdir}/lipidcompass/upload-dir

springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1
  cache:
    disabled: true
