/**
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: nils.hoffmann@isas.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Parameter } from './parameter';


/**
 * The name, source, analyzer and detector of the instruments used in the experiment. Multiple instruments are numbered [1-n].
 */
export interface Instrument { 
    id?: number;
    name?: Parameter;
    /**
     * The instrument's source, as defined by the parameter.
     */
    source?: Parameter;
    /**
     * The instrument's mass analyzer, as defined by the parameter.
     */
    analyzer?: Array<Parameter>;
    /**
     * The instrument's detector, as defined by the parameter.
     */
    detector?: Parameter;
}
