/**
 * mzTab-M reference implementation and validation API.
 * This is the mzTab-M reference implementation and validation API service.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: nils.hoffmann@isas.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * A publication item, defined by a qualifier and a native accession, e.g. pubmed id.
 */
export interface PublicationItem { 
    /**
     * The type qualifier of this publication item.
     */
    type: PublicationItem.TypeEnum;
    /**
     * The native accession id for this publication item.
     */
    accession: string;
}
export namespace PublicationItem {
    export type TypeEnum = 'doi' | 'pubmed' | 'uri';
    export const TypeEnum = {
        Doi: 'doi' as TypeEnum,
        Pubmed: 'pubmed' as TypeEnum,
        Uri: 'uri' as TypeEnum
    };
}
