export * from './collectionController.service';
import { CollectionControllerService } from './collectionController.service';
export * from './lipidDocumentEntityController.service';
import { LipidDocumentEntityControllerService } from './lipidDocumentEntityController.service';
export * from './lipidDocumentSearchController.service';
import { LipidDocumentSearchControllerService } from './lipidDocumentSearchController.service';
export * from './lipidQuantityDocumentEntityController.service';
import { LipidQuantityDocumentEntityControllerService } from './lipidQuantityDocumentEntityController.service';
export * from './lipidQuantityDocumentSearchController.service';
import { LipidQuantityDocumentSearchControllerService } from './lipidQuantityDocumentSearchController.service';
export * from './mzTabResultDocumentEntityController.service';
import { MzTabResultDocumentEntityControllerService } from './mzTabResultDocumentEntityController.service';
export * from './mzTabResultDocumentSearchController.service';
import { MzTabResultDocumentSearchControllerService } from './mzTabResultDocumentSearchController.service';
export * from './profileController.service';
import { ProfileControllerService } from './profileController.service';
export * from './studyDocumentEntityController.service';
import { StudyDocumentEntityControllerService } from './studyDocumentEntityController.service';
export * from './studyDocumentSearchController.service';
import { StudyDocumentSearchControllerService } from './studyDocumentSearchController.service';
export const APIS = [CollectionControllerService, LipidDocumentEntityControllerService, LipidDocumentSearchControllerService, LipidQuantityDocumentEntityControllerService, LipidQuantityDocumentSearchControllerService, MzTabResultDocumentEntityControllerService, MzTabResultDocumentSearchControllerService, ProfileControllerService, StudyDocumentEntityControllerService, StudyDocumentSearchControllerService];
