export * from './controlledVocabularyController.service';
import { ControlledVocabularyControllerService } from './controlledVocabularyController.service';
export * from './crossReferenceController.service';
import { CrossReferenceControllerService } from './crossReferenceController.service';
export * from './cvParameterController.service';
import { CvParameterControllerService } from './cvParameterController.service';
export * from './facetController.service';
import { FacetControllerService } from './facetController.service';
export * from './hasCrossReferenceController.service';
import { HasCrossReferenceControllerService } from './hasCrossReferenceController.service';
export * from './hasCvParameterReferenceController.service';
import { HasCvParameterReferenceControllerService } from './hasCvParameterReferenceController.service';
export * from './hasCvParentController.service';
import { HasCvParentControllerService } from './hasCvParentController.service';
export * from './hasMzTabResultController.service';
import { HasMzTabResultControllerService } from './hasMzTabResultController.service';
export * from './indexController.service';
import { IndexControllerService } from './indexController.service';
export * from './lipidController.service';
import { LipidControllerService } from './lipidController.service';
export * from './lipidMapsEntryController.service';
import { LipidMapsEntryControllerService } from './lipidMapsEntryController.service';
export * from './lipidQuantityController.service';
import { LipidQuantityControllerService } from './lipidQuantityController.service';
export * from './lipidSpaceController.service';
import { LipidSpaceControllerService } from './lipidSpaceController.service';
export * from './mzTabResultController.service';
import { MzTabResultControllerService } from './mzTabResultController.service';
export * from './plottableLipidQuantityController.service';
import { PlottableLipidQuantityControllerService } from './plottableLipidQuantityController.service';
export * from './statsController.service';
import { StatsControllerService } from './statsController.service';
export * from './studyController.service';
import { StudyControllerService } from './studyController.service';
export * from './submissionController.service';
import { SubmissionControllerService } from './submissionController.service';
export * from './swissLipidsEntryController.service';
import { SwissLipidsEntryControllerService } from './swissLipidsEntryController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [ControlledVocabularyControllerService, CrossReferenceControllerService, CvParameterControllerService, FacetControllerService, HasCrossReferenceControllerService, HasCvParameterReferenceControllerService, HasCvParentControllerService, HasMzTabResultControllerService, IndexControllerService, LipidControllerService, LipidMapsEntryControllerService, LipidQuantityControllerService, LipidSpaceControllerService, MzTabResultControllerService, PlottableLipidQuantityControllerService, StatsControllerService, StudyControllerService, SubmissionControllerService, SwissLipidsEntryControllerService, UserControllerService];
